### ISSUE TITLE
ULS UNITS HOTEL - Accessibility assessment

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#113]

**Comment by kevinkidwell** [comment]
We are currently waiting for CIT to perform their manual assessment and will revisit with those results.

**Comment by mhk33** [comment]
One error that comes up is "Link text used for multiple different destinations." Multiple links to the Askk a Librarian triggers this. The Ask a Librarian link in the top header goes to the Email form:
https://www.library.cornell.edu/ask/email

This made me wonder if the librarians requested that the link go to the email form, or if it should go to the Ask a Librarian landing page, which provides other options for contact:
https://www.library.cornell.edu/ask

On other/older unit sites I have linked to the Ask a Librarian landing page. I'm fine either way, just want to make sure we're consistent and Ask a Librarian stakeholders are on board with the link destination, and they want us filtering traffic to the email form first.

**Comment by mhk33** [comment]
SiteImprove issues I am not fixing since they are theme-related and will be changed — documenting these as things to look out for in the new theme:

Errors:
- Link text used for multiple destinations - "Ask a Librarian", "Catalog" (Level A, AA)
- Link identified only by color; link color needs to be 3:1 against text and applied appropriately throughout (accordion link color is different than link color) (Level A, AA)
- Tab sequence is out of order - search overlay doesn't tab correctly (this was corrected in Vet); search dropdown options not keyboard-accessible (Level A, AA)

Warnings:
- Non-distinguishable landmarks - nav, section, etc., need aria-labels (Level A)
- Content not included in landmarks - skip nav should be in a landmark; also search and menu icons (I think) (Level A)

**Comment by mhk33** [comment]
Manual check by CIT:

Physical Science Library -  https://docs.google.com/spreadsheets/d/1ggLYECt1iGmWCK5YokRIuiwKCr7uFOosLALkZxcNmC4/edit?usp=sharing
