### ISSUE TITLE
Olin-Uris changes to latest news on home page

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1200]
From: Adriana Maria Ferreira Barboza <[af582@cornell.edu](mailto:af582@cornell.edu)>
Date: Tuesday, July 25, 2023 at 12:57 PM
To: Jesi Buell <[jcb79@cornell.edu](mailto:jcb79@cornell.edu)>, Alexandra O'Neill <[arj48@cornell.edu](mailto:arj48@cornell.edu)>
Cc: Melissa Wallace <[mhk33@cornell.edu](mailto:mhk33@cornell.edu)>
Subject: Help with HOMEPAGE section of OlinUris

Hi Jessi and Melissa,
 
I need to edit something in the Olin and Uris Libraries homepage but don’t know how to, or rather do not know enough code to be able to do this, could you please help?
 
What I’m trying to do is have the site only pull the latest blog post in the [“Latest Blog Posts” section of the homepage](https://olinuris.library.cornell.edu/), instead of a long list the way it is showing now. We don’t update the blog post that often, so seeing the list makes us loose the newsworthy aspect of it, whereas if we only saw the newest blog post, it would work better for us! We would also like the section to pull the featured image of the blog post together with the title, so it displays in that section as well. Is this possible? It would look much more attractive.
 
Kindly let me know if there’s anything you can do.
Here is the link to the blog, for your reference: https://blogs.cornell.edu/olinuris/
 
Best,
Aia.

**Comment by mhk33** [comment]
To change to one post only:

Dashboard > Aggregator > News feed source

Change the "Limit" field from 5 to 1 and click "Update."

Also there is a setting for "Featured image" further down, but it's not clear to me how to view the feed we get and how to update the home page template. (Is it in the culu theme and therefore shared by all?)

**Comment by sarah-cul** [comment]
@mhk33  I think I figured this out, If it looks ok to you, I will ask the stakeholder to confirm.
https://sac356-news-uls-olinuris-library-cornell-edu.pantheonsite.io/

In the [feed](http://blogs.cornell.edu/olinuris/feed/) there is just one  blog post that has an image but its the 7th post
So in order to see it on the front page for testing purposes...
Dashboard > RSS Aggregator >Templates and edit the "News" template. 
Here you can change the default 9. I also changed the Template Type to Excerpt and Thumbnail. 
(By choosing excerpt, we can fill the empty space when there is only 1 post.)
<img width="450" alt="image" src="https://github.com/cul-it/uls/assets/144364984/d6075a6b-23b5-454b-a939-f519c731c40b">

then I was able to see the post that has a thumbnail... I think it looks ok? 
<img width="300" alt="image" src="https://github.com/cul-it/uls/assets/144364984/276b9c10-8653-44ad-8a47-f9225efb8440">

Now change the Feed Source -> limit to 1:
<img width="400" alt="image" src="https://github.com/cul-it/uls/assets/144364984/9302f637-d15f-47b6-8afa-09fa0d535bba">

<img width="300" alt="image" src="https://github.com/cul-it/uls/assets/144364984/23ec9673-330d-44b5-b4eb-2f0e6690f708">

**Comment by mhk33** [comment]
@sarah-cul Looks great. Does the latest post have a thumbnail? If not, perhaps we just tell Aia to be sure to include one (and it should then show up?).

**Comment by mhk33** [comment]
Also assigned to you if you don't mind working on this... thank you!

**Comment by sarah-cul** [comment]
That last feed item (slope day) does not have a image, there was only 1 post in the feed that did (the one in the screenshot). 
I don't see a way to set a default image, I also don't see a way to edit existing feed items,  but I think it could be done with a code snippet, so if Aia has one that we can show when the latest feed item does not have an image, then I can try to figure that out. I will email and see what their preference is.

**Comment by mhk33** [comment]
OK. I wonder if it can just show an image if there is one, otherwise it's just text. Perhaps she can also add an image to the Slope Day post to illustrate how it will work. Thanks for your help with this!

**Comment by sarah-cul** [comment]
content owner (Leah Dodd) approved the change

**Comment by mhk33** [comment]
Thank you, @sarah-cul!
