### ISSUE TITLE
Add second location to Vet hours on banner

### ISSUE THREAD

**Issue by JesiBuell79** [cul-it/uls#1204]
Email from 8/21:
Hello kind website developer folks,
I’m writing today to ask if it would be possible to show our library’s hours  on our website banner. The current view only shows the full hours for the public. Is it possible to make the font smaller so that both the public and vet community access hours are visible on our website?
https://vet.library.cornell.edu/full-hours/
 
Thanks in advance for your assistance.
 
Warm Regards,
Chris
 
cd332@cornell.edu

This seems like a good project for @mhk33 and @Moemonty to do together for onboarding

**Comment by mhk33** [comment]
For how to display - Olin-Uris shows hours for two locations:
https://olinuris.library.cornell.edu/

**Comment by mhk33** [comment]
From Chris today -- use Mann as the display example:

Good morning IT developer team, 
I was just looking at our website this morning and I wonder if you could make it so that both our public hours and vet community hours are visible on the website banner? 

https://vet.library.cornell.edu/full-hours/

If It's possible, could our banner be similar to the one at Mann:

https://mann.library.cornell.edu/

Thank you so very much. 
Chris

**Comment by sarah-cul** [comment]
This can be done right in the WPAdmin, click on Settings -> LibCal hours.  Choose an optional library department. 

![Screenshot 2023-09-26 at 12 45 46](https://github.com/cul-it/uls/assets/144364984/75cc0165-93e8-4600-80cd-47cd1800c6a5)

![Screenshot 2023-09-26 at 12 40 36](https://github.com/cul-it/uls/assets/144364984/0a7a39da-5bae-4e7f-90d7-73c3023118a3)
