### ISSUE TITLE
Evaluate Draw Attention maps tool

### ISSUE THREAD

**Issue by JesiBuell79** [cul-it/uls#1209]
with stakeholders in Mann (Tobi Hines) and Olin/Uris (Can O'Neill)

**Comment by sarah-cul** [comment]
interactive PDF showing more details (from Craig Mains)
https://acrobat.adobe.com/link/review?uri=urn%3Aaaid%3Ascds%3AUS%3Ab25ffdf6-7afe-3535-a54b-64b2d42fd3ab

Suggestions for what to look for in the plugin we ultimately choose to do the floor plans include:
- accessibility in mind
- search ability
- more details, interactive
- instead of starting by exploring on a chosen floor level, allow the user to find all things they are looking for and indicate that on the map on various floors, allowing the tool to be used the way that the user would need

research what is being used on other institutions websites, airports etc.

**Comment by mhk33** [comment]
Also could maybe link the main site spaces to locations on floor maps. (Integrate the two in some way.)

**Comment by JesiBuell79** [comment]
This is a duplicate - closing this one --
