### ISSUE TITLE
Improve documentation for users

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1214]

**Comment by sarah-cul** [comment]
Need to go through material we have in box, see what we can delete, or update. 
Then create a reference for content owners in confluence... this will link to all relevant documentation that is in box.

**Comment by sarah-cul** [comment]
https://confluence.cornell.edu/display/CULITSD/Content+Contributors+-+Documentation

@mhk33 do you have any suggestions on where we are lacking on documentation, what the content owners might like to have handy? I was thinking of documenting how to change use facets with custom post loops.. i have it in the tech unit site documentation but I could make that more broad.

**Comment by mhk33** [comment]
This looking great! Nice to have it all in one place. I updated this Box note with "developer" and "contributor" notes. https://cornell.app.box.com/notes/1289866551876

Should we add these?:

- managing alert boxes
- adding users (have not checked that contributors can actually do this)
- footer content - contact info and social media links

Do we have central developer documentation for units?

**Comment by mhk33** [comment]
Never mind - I see that's listed as "Unit sites (uls)" and describes what's in there!

**Comment by sarah-cul** [comment]
yes to all those ideas

The user adding is likely only for admins, so that would make sense to have for developer documentation.(did you mean to add a new confluence page for developer documentation?). I had to figure out the custom user roles that some sites have defined, documentation would have definitely been useful.

**Comment by mhk33** [comment]
Yes, maybe we should have a developer documentation page. I keep referring to my little Box notes for how to do things because I forget every time, but maybe it's good to put it in Confluence, too.

**Comment by sarah-cul** [comment]
New confluence page: [Developer Documentation](https://confluence.cornell.edu/display/CULITSD/Developers-+Documentation)

organized into the Department/Unit Page Documentation so that only developers will be able to access this page
We can use that to keep track of things of interest to developers for Unit sites, no matter where we find them.

**Comment by mhk33** [comment]
Thank you, @sarah-cul!
