### ISSUE TITLE
Compare draw attentino with other mapping software

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1215]

**Comment by JesiBuell79** [comment]
from sarah - interactive PDF showing more details (from Craig Mains)
https://acrobat.adobe.com/link/review?uri=urn%3Aaaid%3Ascds%3AUS%3Ab25ffdf6-7afe-3535-a54b-64b2d42fd3ab

Suggestions for what to look for in the plugin we ultimately choose to do the floor plans include:

accessibility in mind (ask Annie Heckel if she has anything to share on this topic)
search ability
more details, interactive
instead of starting by exploring on a chosen floor level, allow the user to find all things they are looking for and indicate that on the map on various floors, allowing the tool to be used the way that the user would need
research what is being used on other institutions websites, airports etc.

**Comment by JesiBuell79** [comment]
Pete Magnus suggested Sassafras?  "We do some usage tracking with it and it does have a mapping service."[https://licensing.citlabs.cornell.edu/maps](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Flicensing.citlabs.cornell.edu%2Fmaps&data=05%7C02%7Cjcb79%40cornell.edu%7C402d1ef5706b4165ef4908dc19314db5%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638412946746569933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5s9GO%2FQwPTP8WEp3c%2Bn3%2B2I5rZHQVmcQ%2FTzDGLo013A%3D&reserved=0)

**Comment by sarah-cul** [comment]
More information on the research into mapping software is found on [jira ticket LP-701](https://culibrary.atlassian.net/jira/software/projects/LP/boards/111?selectedIssue=LP-701)

**Comment by sarah-cul** [comment]
there was a decision to not go forward with the stack maps. All research for this ticket is on LP-701. We have some ideas for improving the draw attention floor plan maps and connecting computer/software availability information & reserve a room with floor maps.
