### ISSUE TITLE
Add Cornell Tech Unit Site

### ISSUE THREAD

**Issue by JesiBuell79** [cul-it/uls#1221]
Jesi's notes from 10/9 meeting - 

Cornell Tech - unit site, “cornelltech” for URL, Christina Sheely would be content owner, “library support” as page title; book delivery/course reserves/staff Marc Reed Hijungin Lee Neeley; build in spring; build from https://guides.library.cornell.edu/cornelltech/home

**Comment by sarah-cul** [comment]
- [ ] Use the LibCal Hours?  https://spaces.library.cornell.edu/hours

- [ ] Who decides on the banner color and hero image

- [ ] Google Analytics property 

- [ ] Organizing the databases, compare how they look:
    [management](https://johnson.library.cornell.edu/databases/) which uses a custom post loop
    [Asia](https://asia.library.cornell.edu/databases/). 282, using a custom post loop
    [Engineering](https://engineering.library.cornell.edu/databases/) 84

    The Physical Science Library unit site is also using a custom post list, it has them grouped into 3 categories: 
[Astronomy](https://physicalsciences.library.cornell.edu/astronomy-databases/), [Chemistry](https://physicalsciences.library.cornell.edu/chemistry-databases/),  and [Physics](https://physicalsciences.library.cornell.edu/physics-databases/)

   PSL might be a good model for Cornell Tech because it is organized into 3 categories as well: 
[Business Research](https://guides.library.cornell.edu/cornelltech/business-research), [Law Research](https://guides.library.cornell.edu/cornelltech/law-research), [Tech Research](https://guides.library.cornell.edu/cornelltech/tech-research)

   OR shoudl we do what [Catherwood](https://catherwood.library.cornell.edu/) does, which is to just link to the databases on the catalog site that are[ pre-filtered by subject ](https://catalog.library.cornell.edu/databases/subject/Human%20Resources,%20Labor%20&%20Employment  )

**Comment by sarah-cul** [comment]
Marc Reed confirmed that course reserves should not be included on the site at this time.

**Comment by sarah-cul** [comment]
GA4 property was added, and exactmetrics plugin configured
siteimprove request was made

**Comment by sarah-cul** [comment]
new site was added to siteimprove
GA4 is collecting data
