### ISSUE TITLE
change font type unit sites

### ISSUE THREAD

**Issue by sarah-cul** [cul-it/uls#1247]
Update the unit sites to use freight-sans-pro font family, https://brand.cornell.edu/design-center/typography/
Checklist for ULS:

- [ ]  Africana
- [ ]  Annex
- [ ]  Asia
- [ ]  Catherwood
- [ ]  Engineering
- [ ]  Finearts
- [ ]  Hotel
- [ ] Law
- [ ] Management
- [ ] Mann
- [ ] Math
- [ ] Music
- [ ] OlinUris
- [ ] PSL
- [ ] Rare
- [ ] Tech
- [ ] Vet

**Comment by sarah-cul** [comment]
<img width="1485" alt="image" src="https://github.com/user-attachments/assets/38e516d6-a201-4856-a0ec-3f45212f0355">

**Comment by sarah-cul** [comment]
@mhk33 turns out the font types are set in the culu theme, when I made the change I noticed the new fonts are smaller so I had to make a few minor adjustments to the padding for the button and increased the size of the "Search" label. Do you think this is ok, or should i increase the font size slightly everywhere?  Even the hero title library name is smaller now.

**Comment by mhk33** [comment]
@sarah-cul Yes, Freight is a smaller font and I've had to adjust the sizing on the various sites where I've used it. You could maybe change the overall font size in the body tag and see if that works nicely. For example, instead of `font-size: 1rem`, change it to `1.1rem` (or use percentage, em, whatever makes sense).

I opted not to do it this way on the main site, in order to keep the sizes "true." Instead I changed elements manually throughout the scss partials. This was more work, but I was reviewing everything closely anyway so didn't really mind.

**Comment by mhk33** [comment]
@sarah-cul I realized I'm not sure I answered your question exactly... I also think it looks OK in the screenshots, even the site title. Mostly I have found the need to bump up the body font (`<p>` and such), but it looks OK to me here. If you get it up on a test site I'm happy to take a look there, too.

**Comment by sarah-cul** [comment]
@mhk33 thanks for the feedback..  I will let you know about a test site that would be great to have another person test it out. I'm working on playing with font sizes now and its looking similar to the previous proportions. I want to roll this out for the next upstream since its a culu theme change.

**Comment by sarah-cul** [comment]
This work is completed in [v1.7.6 of the culu theme](https://github.com/cul-it/wp-cul-theme-culu/releases/tag/v1.7.6) so it will roll out in the next upstream
