### ISSUE TITLE
Research the work on equipment reservation done so far

### ISSUE THREAD

**Issue by tahirpoduska** [cul-it/uls#143]
Manolo has shared some documentation from the space usage committee and also the work he did with Nick.

**Comment by tap87** [comment]
Copying the findings of the usability committee:
Findings
[Streamlined-equipment-201708.docx](https://github.com/cul-it/uls/files/2876894/Streamlined-equipment-201708.docx)

1.	Patrons cannot go to one website to get equipment information and availability. They need to visit (and learn to use) over a dozen different sites to see what each library individually holds.
2.	Only two libraries (Olin/Uris, Mann) appear to have a large amount of equipment represented on their website. It is unknown if other libraries don’t include more equipment information because of scale, lack of use or demand, or due to challenges around providing and maintaining this information.
3.	There is a great deal of inconsistency between sites with respect to equipment offered, policies, terminology for both the equipment and how the service is named, navigating to the service information, and level of detail provided.
4.	Most sites did not offer information about availability.
5.	Like Cornell, other libraries are struggling with how to manage and promote an ever changing array of equipment, though there do exist interesting examples from which we can learn.
