### ISSUE TITLE
Start basic plugin work for equipment reservation

### ISSUE THREAD

**Issue by tahirpoduska** [cul-it/uls#151]
Based on the discussion with @manolobevia, we think that the equipment reservation has lesser scope than the space reservation and can get some basic work done in this sprint. However, I think that both the space and equipment reservation should be looked at as one system and we should meet with stake holders to define the scope and requirements for such a system.

**Comment by tap87** [comment]
So far, I have been working on the architecture of the plugin to mimic the LibCal API. We can have the plugin on a site where we can display spaces and equipment from all libraries and the customize the plugin for an individual unit library to display the spaces and equipment for just that library. At this point, I don't think we can make much progress on the plugin since we need to discuss the user workflow for reserving spaces and equipment, the policies across various libraries and trying to consolidate them as well as figuring out whether a plugin is the ideal solution or a separate app would be better.

**Comment by tap87** [comment]
Moving this to backlog till we have a meeting about how to implement

**Comment by JesiBuell79** [comment]
Closing - reconfiguring how we're doing this --
