### ISSUE TITLE
Olin/Uris

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#188]
Olin/Uris Accessibility Remediation

Number of issues: 42
Current score: 62.9%
PDF errors: 17

**Comment by mhk33** [comment]
The chat widget uses HTML for presentational attributes. The markup for this comes out of an embed script. I thought we should check if there is updated embed code since this probably hasn't been modified in a long time. Virginia says there probably isn't, but Springshare just bought their chat software so she'd like to leave the widget a little longer to see if Springshare will be making changes to it.

**Comment by mhk33** [comment]
The bulk of the work is done. I will create issues for anything outstanding, such as PDF remediation.
