### ISSUE TITLE
ULS UNITS - Management Library

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#196]

**Comment by kevinkidwell** [comment]
Notes from 6/17/19 meeting:

- [ ] Search box on the homepage should default to Site Search instead of Catalog
- [ ] Databases/FAQs will be added as posts and tagged to be searchable - can be added by students when ready
- [ ] Layout adjustment to add box next to the Library Name box to be able to include course reserves
- [ ] Remove Ask a Librarian from header bar and add it to the Library Name bar
- [ ] Change email icon and Ask a Librarian to link to the Qualtrics contact form (or should it be a mailto link for one of them?)
- [ ] Groups feed should paginate with a limit of 10-15 per page
- [ ] Need to talk to LTS for the New Books feature to see what can be done for them (want to keep this feature - books are housed in ILR - current new books is using holdings.loc:jgsm)
- [ ] Hours plugin needs some adaptation to be able to select the hours - how can this display multiple hours? - Jim able to work on? - They need to display the Help Desk hours
- [ ] Unit school name in the header should be changed to the logo image for branding
- [ ] Popular Databases and Topics are added by hand
- [ ] Look for a plugin that will display a featured topic that shows a random one from a set when the page is loaded (maybe from a "featured" category or tag?)
- [ ] Need the capability to add other search terms for databases that students may search or know those databases as
- [ ] Test a hidden input within a database custom field creation to see if it is searchable
- [ ] Customize the display of search results to always show Databases first and then FAQs/Topics/etc.

- [ ] Rachel to add Information Architecture sheet to Box

**Comment by kevinkidwell** [comment]
@manolobevia Do you know where we got the URL for the Campus Groups events RSS feed for Management? Drupal has this (https://johnson.campusgroups.com/mgmtlibrary/rss_calendar?filter=future) as the feed URL but putting it into our WP Aggregator, it says the feed isn't valid so it won't import it. I'm wondering if there's a different feed that we may be able to use or if I need to get in touch with someone in the Johnson school about it.

**Comment by manolobevia** [comment]
Sorry, I don't know @kevinkidwell. @mhk33 might know.

**Comment by mhk33** [comment]
Sorry, I don't know why it works in Drupal but WP Aggregator can't use it. Maybe worth asking someone at the Management Library if there is a different feed. I was looking here, but didn't see a way to get RSS:
https://johnson.campusgroups.com/calendar
