### ISSUE TITLE
ULS UNITS - ILR

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#198]

**Comment by kevinkidwell** [comment]
@manolobevia We met with ILR for the initial meeting yesterday and while we didn't talk about features, it got me thinking about how we may want to set up some of their things. Are we using a Custom Post Type plugin in the CULU theme right now? That might be a good way to go for ILR because they have Workplace Issues Today and Book of the Month which are both blog post-type things but with set field groups and I wonder if having a CPT would be best to keep them separate for students/staff adding those instead of all as just a Post.

**Comment by manolobevia** [comment]
@kevinkidwell I had before a CPT plugin installed in CULU (custom post type UI), but was difficult to create metaboxes and custom fields, that's why I got ACF plugin. There are always different ways to do things, for staff pages, core books (PSL), databases (psl)  "post types", etc I have used ACF. Then I have created specific templates that invoke specific fields (ACF). If  you need a CPT plugin (`https://www.codeinwp.com/blog/top-custom-post-types-plugins-for-wordpress/` or others), I can put it at CULU level so all units can use it. I prefer ACF because has a huge variety of custom fields already created. If we can get a Custom Post plugin that works with ACF that would be great. Also, we could create a POST object with ACF (`https://www.advancedcustomfields.com/resources/post-object/`)

**Comment by kevinkidwell** [comment]
I think it would be good to have one for instances like this, then we can really control what gets displayed for those who editing certain types of content and be able to more easily create display pages for all posts of a certain type.

On [AgCensus](http://dev-agcensus-test.pantheonsite.io/), I'm using ACF Pro, [CPT UI](https://wordpress.org/plugins/custom-post-type-ui/), and Elementor Pro. With this setup, I was able to create the fields in ACF and then restrict them to a specific post type created with CPT, hide all of the unnecessary elements from the post creation with CPT so only the ACF fields are there, then use Elementor to create a template for that post type that pulls the information from ACF for those individual posts.
