### ISSUE TITLE
ULS UNITS - Fine Arts

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#204]

**Comment by manolobevia** [comment]
Created a few visuals for the 
![Home page](https://user-images.githubusercontent.com/8395482/56933971-26dc2880-6ab8-11e9-93d3-4c2dccb54c3b.png)
![Interior page](https://user-images.githubusercontent.com/8395482/56933972-26dc2880-6ab8-11e9-9c36-835f4ab5f869.png)

client.

**Comment by manolobevia** [comment]
Some Matomo metric info to pay attention:

Visitor overview:
https://webstats.library.cornell.edu/index.php?date=2018-04-27,2019-04-27&expanded=1&filter_limit=100&format=XML&format_metrics=1&idSite=29&method=API.get&module=API&period=day&token_auth=17caefd465e774bb7cd61888ce12c198

Pages view, bounce rate, exit rate, etc
https://webstats.library.cornell.edu/index.php?module=CoreHome&action=index&idSite=29&period=day&date=yesterday&updated=1#?idSite=29&period=range&date=2018-04-27,2019-04-27&category=General_Actions&subcategory=General_Pages


Acquisition:
https://webstats.library.cornell.edu/index.php?date=2018-04-27,2019-04-27&expanded=1&filter_limit=100&format=XML&format_metrics=1&idSite=29&method=Referrers.getReferrerType&module=API&period=day&rows=Direct+Entry,Total&token_auth=17caefd465e774bb7cd61888ce12c198


Keywords not define on matomo
“Keyword not defined” means the search engine did not pass to your website the keyword used by your visitors — Search engines hide the keyword for privacy reasons. This started in early 2012 but now in 2017 there is now a powerful solution to get back your search keywords reports in Matomo
https://matomo.org/faq/general/#faq_144

**Comment by manolobevia** [comment]
Pantheon DEV's site: `wp-ci-finearts-library-cornell-edu`

**Comment by kevinkidwell** [comment]
Once we start discussing this with the stakeholders, we'll need to share the designs and talk with them about the process we are doing for content review and migration.

If we are going with Fine Arts next, we need to create a form for them off of our Content Review Template (https://cornell.app.box.com/file/441876013896) and explain the process for the review and then how we're going to get them migrated once they've finished with the review.

**Comment by mbmartini** [comment]
@kevinkidwell that box link isn't working for us - I suspect the file/folder is locked down and needs permissions edited to allow access.

**Comment by kevinkidwell** [comment]
I forgot about that, I just added you and Manolo to the folder so you should be able to see it now!

**Comment by manolobevia** [comment]
@sew268 based on this template, how stakeholders measure `user Impact`?

**Comment by sew268** [comment]
@manolobevia thanks for asking and this may need a little tweaking. :)  Basically, I wanted to get each stakeholder thinking about how any changes might affect their users or why *no* changes were crucial because it would have negative impact on their users if it disappeared.  Having a separate column may be a little confusing so what I might do is put this as something to address in the comments section.

**Comment by manolobevia** [comment]
The idea is great, but stakeholders won't provide any Quan or Qual data that support their assumptions. For example, PSL will tell you that `https://physicalsciences.library.cornell.edu/category/chemistry-databases/` is extremely valuable for the users, `we must keep this...`. If you check web metrics, there are only 48 unique page views (% of Total: 2.23% (2,154) ), since the site was launched 5 months ago. The form is great, it gives them an opportunity to clean up content.

**Comment by sew268** [comment]
@manolobevia thanks for your feedback and I'm glad you like the form!  I hear you on the stakeholders and you're right, it will be a 'perceived' impact but it is one piece of data to add to the web metrics that I think will be worth considering when we make a determination to either keep or toss a feature or content.  Kevin is adding the web metrics to the forms so that stakeholders will see page traffic...maybe that will help them be a little more honest in determining user impact. ;)

**Comment by manolobevia** [comment]
@sew268 that's a great idea!!!!!!!

**Comment by manolobevia** [comment]
I have created a child theme of CULU theme instance (using custom stream) for Fine Arts to start migrating content when they are ready.
Pantheon instance name: `**uls-finearts-library-cornell-edu**`.
DEV ULS: `https://dev-uls-finearts-library-cornell-edu.pantheonsite.io/`

**Comment by kevinkidwell** [comment]
Meeting with Marsha:
- Deadline to launch site is August 5th, when new building opens
- Is there a way to keep an archived version of the site? Just afraid of potentially losing content

**Comment by manolobevia** [comment]
For how long? If we keep the current site (archived), this means we have to pay for this site and continue doing Drupal updates. Maybe @jgreidy has a better solution.

**Comment by mhk33** [comment]
Just a note that the site should be crawled in archive.org, and we can ask Michael in Metadata Services to get a snapshot prior to taking down the old site. I imagine the old Pantheon Drupal site can stay up for a little while, at least.

**Comment by kevinkidwell** [comment]
More notes from the meeting:
- If archiving, what would happen with the images? Or what is happening with images currently in drupal that are moving to WP?
- Looked at Vet on Chrome and noticed that the College name/link starts overlapping the image when the window shrinks and the menu icon doesn't show up immediately when the College name goes away.
- Would there be a way to change the Library name font, potentially a list of a few fonts to choose from?

**Comment by manolobevia** [comment]
- If archiving, what would happen with the images? Or what is happening with images currently in drupal that are moving to WP? `should we go with archive.org?`
- Looked at Vet on Chrome and noticed that the College name/link starts overlapping the image when the window shrinks and the menu icon doesn't show up immediately when the College name goes away. `College name is removed for now from the top. College presence is at the bottom`
- Would there be a way to change the Library name font, potentially a list of a few fonts to choose from? `We will have one font across all the unit sites for the current library name font`

**Comment by manolobevia** [comment]
RE: archiving FINEARTS, I have opened a new issue. https://github.com/cul-it/uls/issues/340`
