### ISSUE TITLE
ULS UNITS Create style guide

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#24]

**Comment by mhk33** [comment]
Thanks, Kevin, great idea!

**Comment by kevinkidwell** [comment]
Elements that should be included in the style guide. This will keep evolving as the project continues to expand and if I run across anything else that should be here.

- CUL Logo
- Navigation
- Header Image
- Header elements
- Links
- Buttons
- Layouts
- Icons
- Footer Logo
- Typography
- Images
- Colors (backgrounds, links, buttons, etc.)

**Comment by kevinkidwell** [comment]
[ULS_Units_Style_Guide.pdf](https://github.com/cul-it/uls/files/2865687/ULS_Units_Style_Guide.pdf)

**Comment by ajs17** [comment]
how is this related to #23 ? Are they duplicate issues?

**Comment by manolobevia** [comment]
@ajs17 I envision to have a design system [ [sample](https://designsystem.digital.gov/) ] for the whole project, where it will include: the main library site + all the units sites [#24](https://github.com/cul-it/uls/issues/24). To be honest with you, it is to early to start creating style guides, the unit theme is evolving and nothing is finalized yet. Also, CLO (branding team) will probably change the whole theme, branding, etc, and they will probably take care of building a design system.

**Comment by kevinkidwell** [comment]
I put together a beginning style guide (posted above) to at least give an initial look of where the units currently are. In my opinion, this is actually already late to be starting a style guide since I like to do them at the very beginning of a project. And any of them that we do with this need to be a living document that can change as the project moves forward, that's just the nature of this one so that's how I did this guide. 

With this we can at least give it to Zsuzsa's team to be able to look over where we are and it gives them a good starting point as well as shows where we currently are so that if changes are made, we know where they are and we can open it up to more conversation from both sides.
