### ISSUE TITLE
ULS UNITS -  Identify user roles and capabilities

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#25]

**Comment by kevinkidwell** [comment]
When working with the PSL stakeholders, I found out that they were not able to view the Appearance menu to be able to do any customization or add sub-menu items themselves. Since that is a big feature we are working with, they should have these abilities.

In saying that, I also don't think that we should make them Administrators because we don't want them to be able to add new plugins or update various things within the site that haven't been tested.

I am going to do some research on some plugins that may allow us to create custom roles where we can set what can be accessed. I would appreciate any feedback or anything else in this train of thought that should be considered (what all they should be able to do, what they shouldn't be able to do, any plugins known already for this, etc).

This can also tie into #82 in decided what role users should have when signing up.

**Comment by mhk33** [comment]
On the current main site, I set some pretty strict restrictions. Contributors are not allowed to create new pages or administer/edit the menu. This was because the previous site (pre-2014) had so many orphan pages and we did a big clean-up of many old, outdated pages that were still findable by Google. Contributors currently ask me to add new pages or make menu changes; I rarely push back on the requests, but it is mostly so that pages don't get lost within the architecture of the site. This is also because we don't really have a content manager (besides me, sort of) to approve or vet requests.

When we first made these changes, I heard about it from some contributors. I don't know that they love that they can't create pages or edit the menu, but they've gotten used to it.

For unit sites that I've done, I haven't set up as many restrictions, though I was a little less concerned about orphan pages and menus getting out of hand. As far as I know this been a problem for most unit sites.

I will try put together a spreadsheet that we can edit for developing the permissions matrix. Please share any info you find on creating custom roles.

**Comment by kevinkidwell** [comment]
I think doing a permission matrix would be great. Do you think we'll need to have two different sets of permission, one for main CUL and one for units? Depending on how granular we feel we need to get, that will inform which plugin would be best for us to use. 

After doing a quick search and testing them out on a local instance, I found a couple of plugins that may work.

https://themehybrid.com/plugins/members
This one has a nice interface with checkboxes and mimics the main sidebar menu to be able to let us choose what users in the role we create can access. One downfall to this one is that it doesn't seem to allow us to pick items within, say, the Appearance menu so that users in a role could only access Customize or Menus but not the others. They either have the ability to edit/change/delete/add themes or adjust theme options (customize/menus/widgets) with no in-between of selecting specifics. Even the purchasable add-ons don't add really useful functionality.

https://www.role-editor.com/
This interface isn't nearly as nice because it doesn't show what options go with which menu item but it has the same basic functionality. This one specifically mentions 'Block selected widgets under “Appearance” menu for role' as a feature of the Pro version. It also has the option to add custom capabilities so if we would ever have anything like that, we can add it in to the roles that way. Pricing on this one: Pro Unlimited Lifetime - $318 for plugin lifetime access.

https://wordpress.org/plugins/wpfront-user-role-editor/
This one is similar to the previous one but has a slightly nicer interface (it's middle of the two). It has the same capabilities of the previous one and one of the screenshots actually has it so that we can remove the ability of roles to get into certain menu options in the Menu Editor. This is the first one with that feature that I've seen documented and is what I was looking for and would be nice depending on granularity. Pricing on this: $129.99 - Unlimited if we don't need Multi-Site support, $149.99 if we do.
More pricing info with their features table: https://wpfront.com/user-role-editor-pro/

**Comment by kevinkidwell** [comment]
I wanted to jot this down while I was thinking of it. We will also need to consider if there are plugins that users are allowed to access and ones that they are not, and where we can restrict that. This thought came out of working with the Importer this morning, which is not something I think should be open for everyone to use, so there may be other plugins like it that we need to consider.

**Comment by manolobevia** [comment]
Duplicated issue.
