### ISSUE TITLE
ULS UNITS - Search - Style search results

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#321]
The current search results do not seem to follow the same page layout kind of style that we have on the rest of the site. They are stretching all the way to the left and should better match how we're going to display content in a list (like databases and FAQs).

For reference, here's how I'm styling the databases on Management to give each result some separation:
![Screen Shot 2019-07-03 at 8 46 47 AM](https://user-images.githubusercontent.com/29164102/60592755-4705bd80-9d6f-11e9-8370-66d3e01a340e.png)

**Comment by manolobevia** [comment]
Search on CULU is styled: `http://dev-culu-library-cornell-edu.pantheonsite.io/?s=About&search-type-home=site`. It is a search on the entire site. 
 It sounds like this is a special kind of search since management doesn't want to search on the site, just databases. Correct?

**Comment by kevinkidwell** [comment]
This is using the same search that is used for the entire site. The current styling of the search results did not work with custom post types or utilize the styles that are used for their other archive-type pages.

The styling of the current site search results doesn't match what was necessary for Management so this was customized on their site using the Snippets plugin and custom CSS. This doesn't just adjust styling for databases but also for their entire site search results to better match the rest of their pages. This has been completed already specifically for their site with the ability to be done on any other unit site that may do this kind of layout by adding it into the Snippets plugin.

**Comment by manolobevia** [comment]
Ok. Cool.  We should integrate this on `culu` for sites that need this type of rich search. 

I did a search `https://dev-uls-management-library-cornell-edu.pantheonsite.io/?s=Provost+lugsail&search-type-home=site` and I think you should remove the `sort by topic` when no content or the sort by type when searching for content on pages. The type `Pages` is not really useful.

<img width="1160" alt="Screen Shot 2019-07-17 at 6 41 21 PM" src="https://user-images.githubusercontent.com/8395482/61416802-fdff4e80-a8c2-11e9-82dc-1094fbfe459b.png">

There is a problem using the snippets plugin if this is used on `culu`, since snippets are added to the database. When we add a db change in CULU, we have to manually add this content to all unit sites, so we don't override the DB on the unit sites from CULU. I know we could export the snippet and imported to all the unit sites but that is so much time-consuming. We should talk about this issue.
