### ISSUE TITLE
Jabbr

### ISSUE THREAD

**Issue by sew268** [cul-it/uls#328]
Look into updating current Jabbr site or bringing into WP as a plugin or comparable solution

**Comment by kevinkidwell** [comment]
Looking at the code and how Jabbr is used to pull the data in (it's a manual process) from Voyager, I think we're in a better place right now to just remediate the site in place and add some styling/links to bring it more in line with the main site.

Once FOLIO rolls out, I would recommend seeing if we can make this a WP plugin that can potentially automatically pull the data from the system instead of having to be done manually, if we can.

**Comment by mbmartini** [comment]
Jabbr is out of scope for the current project. It is not a CUL-IT supported service, and would need to be scoped independently to include ongoing maintenance effort.
