### ISSUE TITLE
ULS UNITS - Footer Contact Info Adjustments on CULU.

### ISSUE THREAD

**Issue by sew268** [cul-it/uls#401]
Makerspace - does not have a Circulation or a Reference Desk; they have 1 "Help Desk".  Can we add Help Desk as an option?  And if there is no phone number that is appears next to a desk location, that desk location doesn't appear in the footer?  In other words, only show fields that are populated?  

Mann will also need this feature as well as the Annex.

**Comment by manolobevia** [comment]
@sew268 We shouldn't display the label if there is no content. 
I have followed `https://www.library.cornell.edu/libraries`, which displays reference, circulation, and email, that's why we have those fields. Makerspace is not part of the list of libraries on `https://www.library.cornell.edu/libraries` 
I am going to create the functionality for letting users introduce on the footer section whatever they want to add (phones and emails contacts).

**Comment by manolobevia** [comment]
Note: Test kirki repeater module, `https://kirki.org/docs/controls/repeater`

**Comment by sew268** [comment]
@manolobevia thanks!

**Comment by manolobevia** [comment]
I have fixed: If there is no phone or email, we won't display the label.

**Comment by manolobevia** [comment]
Expended a lot of time or Kirki repeaters, and the samples on Kirki site don't even work. I'll do more research. Another option is to create a widget, not ideal. Some content is added via customizer and other from a widget.

**Comment by manolobevia** [comment]
@sew268 Ok. I was able to add this new functionality.

Right now, we can add any type of email or phone number.

Go to Admin/ Customizer/ Add Contact Info/ Contact (emails/phones) to add phone and emails.

Since we have a new way to do this, we will have to introduce again this type of content. 
I will do Hotel, Vet, and Fine arts. No needs to do PSL since they have a custom footer. The rest of the sites need to be updated. You can try on culu `http://dev-culu-library-cornell-edu.pantheonsite.io/`, the rest of the sites need to be updated once Jim is back.
