### ISSUE TITLE
ULS UNITS - Branding - Unit Name

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#411]
Since the logo will be using Montserrat sans-serif, it would make sense to tie the Unit Name branding in with the overall Library branding. Montserrat is a Google Font so we can easily add it in to be used. (https://fonts.google.com/specimen/Montserrat)

We were previously going to send out a survey to stakeholders about font choices but this is a more cohesive way to go.

**Comment by manolobevia** [comment]
We haven't decided will be using Monserrat sans-serif. Also, Merriweather is a google font too. 

I did 4 mockups with sans serif versus serif, uppercase, and letter case samples. The only client that argue about the library name font was Marsha. After I sent her the four variations, I also explained to her that I want to let the user know very clearly where they were, not CUL but the unit library that's why I wanted to visually communicate that by using a Serif font. She said I agree with you. How many clients have complained about this? 

![Screen Shot 2019-08-13 at 10 55 40 AM](https://user-images.githubusercontent.com/8395482/62952522-cc8e7b80-bdb9-11e9-9924-f1ea04b3564a.png)

**Comment by manolobevia** [comment]
And please send the survey to the stakeholders. We should use what the majority want, not what you or I want.

**Comment by kevinkidwell** [comment]
We are up to 3 groups of stakeholders that have brought this up. Montserrat is what is used in our print presence, so to use it would be a more unified library brand instead of choosing some other font that we want instead.

This seems to be more of a brand decision than a design decision.

**Comment by manolobevia** [comment]
3 is not the majority. We should have a survey.  It is a brand decision and a UI issue too, but we don't have any brand representation that's why we should do a survey with the stakeholders. 

Sending mockups.

![SanSerif-Lettercase](https://user-images.githubusercontent.com/8395482/62953077-d9f83580-bdba-11e9-8c02-4cf673e31f1e.png)
![SanSerif-uppercase](https://user-images.githubusercontent.com/8395482/62953078-da90cc00-bdba-11e9-8fb4-411fc85f0561.png)
![Serif-Lettercase](https://user-images.githubusercontent.com/8395482/62953079-da90cc00-bdba-11e9-9bc6-2b54e7660046.png)
![Serif-Uppercase](https://user-images.githubusercontent.com/8395482/62953080-da90cc00-bdba-11e9-97a1-1a53e6c10ebc.png)

**Comment by manolobevia** [comment]
From Sara:

```Thanks Manolo.  I agree with you that this is about what everyone (or at least the majority of folks) will be happy with. 

We’ll definitely still do a survey and Kevin and I can work on that next week.

-Sara```

**Comment by kevinkidwell** [comment]
Perhaps we should bring in someone who is an authority on Library branding to weigh in on what should be done, then, before sending out a survey. I want to make sure we have designs with the correct fonts and options that we need to be using to stay on brand.

**Comment by manolobevia** [comment]
We don't have any branding. We have a new logo identity created 3 years ago, and It wasn't approved by LEG, other libraries, etc. So there is no official CUL branding.

**Comment by kevinkidwell** [comment]
Let's put a meeting on with Zsuzsa, Carla, and all of us to see if we can get some answers on the branding before moving forward with any of this. I'll look for a time that will work for all of us and put it on the calendar.

**Comment by manolobevia** [comment]
[cul-branding-variations.pdf](https://github.com/cul-it/uls/files/3497786/cul-branding-variations.pdf)

That is the only thing we have for  CUL logo, created in 2015. We shouldn't talk about branding because we don't have a CUL branding. First, the brand needs to be created, then you create assets (ex: logo, print material, etc) to support the brand. 

So you want to have a meeting and follow what is attached. Correct? We are not talking about changing the font. If that is the case we need to follow the visual identity created (sample `https://africana.library.cornell.edu` ). Because if you just want to change the font, you are not following the current guidelines either. We will have to do a new redesign for the CULU theme, stop any future site launch and introduce this big change.

**Comment by mbmartini** [comment]
Library branding was put on hold earlier this year. Zsuzsa attempted to pursue it with Gerald multiple times to no effect. At that point it was decided by the AUL's sponsoring the CLO/ULS project to put it on hold and go forward with what was originally developed. We may revisit branding next calendar year, but for now that is not on the table.
