### ISSUE TITLE
ULS UNITS - Change "Book a Consultation" to "Book a Meeting" on profile pages.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#496]
Vet has requested to change "Book a Consultation" to "Book a Meeting" What do you think @mhk33 @kevinkidwell ? I can't do just a change for Vet, all the sites will have this change too.

**Comment by kevinkidwell** [comment]
Is the only site that is using this besides Vet right now PSL? Eventually Mann will need something but they've also changed their consultation model so that it isn't on a single person, but goes to a group instead. This will be a spot that we'll have to conceptualize more later. 

Maybe this is something where we should use `get_field_object()` (https://www.advancedcustomfields.com/resources/get_field_object/) to show the text of the button to be the field label that we define in the custom post type?

**Comment by mhk33** [comment]
I don't have strong feelings about this, but "book a meeting" makes me think of book a meeting room, and not necessarily a meeting with librarian. But maybe they've already investigated that this is a better label?

**Comment by manolobevia** [comment]
Yes, Vet and PSL.  We can add another custom field to the staff post, but we should be consistent. 

RE: But maybe they've already investigated that this is a better label? Vet just want to change the wording. That's all.  From Paige: We'd also like to change the wording a bit, from "Book a Consultation" to "Book a Meeting."

**Comment by mbmartini** [comment]
Maybe "Book an Appointment"?

**Comment by kevinkidwell** [comment]
I think this would be better to have a chat with Paige to see why they want to make this change. @manolobevia will you forward the email/message about that on to Sara and I and we can respond to see why they want to change. We also have the content editor training so that may help get them around to what can really change easily and what can't/shouldn't because it affects everyone.

**Comment by manolobevia** [comment]
Done!
