### ISSUE TITLE
PSL - set up analytics

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#52]
- [x] GA Setup
- [x] Add GA [plugin](https://wordpress.org/plugins/ga-google-analytics/)
- [ ] Add GA code to theme

**Comment by kevinkidwell** [comment]
I was just looking at this to see if it was something I could do (it isn't since I can't add a new site to our GA account) and I noticed that PSL already has the GA plugin. It was also still using the code from Vet so it has recorded all of the stats of what we've been doing on PSL. If we ever need to pull stats from Vet, we'll have to go through and sort those out.

**Comment by manolobevia** [comment]
GA Tracking code: UA-8097093-38
Add when site is ready.

**Comment by manolobevia** [comment]
@kevinkidwell my bad. Don't worry too much, VET has minimum traffic.
