### ISSUE TITLE
ULS UNITS - Create demo ULS site for training uls curators using private upstream

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#535]
Pantheon name: `uls-demo`
URL: `https://dashboard.pantheon.io/sites/b86a218e-9ce6-44e8-b920-632af323d437#dev/code`

**Comment by manolobevia** [comment]
After accessing new site I get this error message:
```Warning: require(/srv/bindings/598a37894bb24f519f1f851dd01d72f6/code/web/wp/wp-blog-header.php): failed to open stream: No such file or directory in /srv/bindings/598a37894bb24f519f1f851dd01d72f6/code/web/index.php on line 6 Fatal error: require(): Failed opening required '/srv/bindings/598a37894bb24f519f1f851dd01d72f6/code/web/wp/wp-blog-header.php' (include_path='.:/usr/share/pear:/usr/share/php') in /srv/bindings/598a37894bb24f519f1f851dd01d72f6/code/web/index.php on line 6```

@jgreidy Please take a look when you can.

**Comment by manolobevia** [comment]
@kevinkidwell when do you need this?

**Comment by kevinkidwell** [comment]
As soon as we can, the training is Thursday, Nov 14th and we need time to get in and add some examples of content that will show issues in SiteImprove. This training is on using SiteImprove and browser extensions for accessibility.

This will be added to uls-mann-library-cornell-edu in Pantheon, right? All unit stakeholders have already had that added to their SiteImprove accounts by CIT, so that we can just use that instance for the training and then remove all our training examples and use it for Mann content.

**Comment by manolobevia** [comment]
I am creating this site, `http://dev-uls-demo.pantheonsite.io/`, for demo purposes, show widget samples, style, siteimprove, etc. We should keep this site.
Then, I can setup Mann for adding content, and you can start working on that. As soon as @jgreidy fix `http://dev-uls-demo.pantheonsite.io/`, I will have a CULU instance on the demo and MANN.

**Comment by jgreidy** [comment]
You are admin.
