### ISSUE TITLE
ULS UNITS - Improve search display on CULU template

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#544]
- [ ] Change `Older posts` and `Newer posts` label links for  for `Back` and `Previous`
- [ ] Add some visual separation
- [ ] When user search custom post types content, it only display post titles. Also the link for those title will takes us to the content type content which only displays the title

Replicate:
Search `math` on Math site, `https://dev-uls-mathematics-library-cornell-edu.pantheonsite.io/?s=match&search-type-home=site`.
Click on this links, `Opere matematche; memorie e note pubblicate`
It just display the title, it should display all the metadata associated to that post.

**Comment by kevinkidwell** [comment]
What's happening on the Math site is because that's a custom post type without an Elementor Single display template for it. I've created that template on most units but hadn't gotten to it for all of them. We should check each unit that has CPTs and make sure single item displays showing the metadata.

**Comment by manolobevia** [comment]
Created individual issues.
