### ISSUE TITLE
ULS UNITS - Make background for header section for CUL links red.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#585]
@kevinkidwell I have noticed so many units are using different colors. We should make this section consistent across all the sites to establish a clear visual separation of what is related to CUL and the unit.

This is how units should look.
![Screen Shot 2019-11-06 at 12.17.30 PM.png](https://images.zenhubusercontent.com/58ffa2ca51aa2c30577c6f84/0bf404c6-7ee3-4e9f-9a53-a752039637af)

Not clear visual separation.
![Screen Shot 2019-11-06 at 12.17.48 PM.png](https://images.zenhubusercontent.com/58ffa2ca51aa2c30577c6f84/68f89ce8-f3a2-436c-a089-77b045b49d27)

![Screen Shot 2019-11-06 at 12.18.03 PM.png](https://images.zenhubusercontent.com/58ffa2ca51aa2c30577c6f84/6b4049b0-c001-459e-b824-da524b7dd9d7)

**Comment by kevinkidwell** [comment]
All of the units have both header banners as the same color. Units did not like that these were two different colors and it made it more difficult to select a header image for some of them. They also did not like it being red because it drew more attention to that navigation and away from the unit's content itself when visiting a page.

Doing the usability test with Fine Arts, students didn't care what was CUL and what was unit with those items so I don't think we need to make those first nav items stand out any more than they already do.

**Comment by manolobevia** [comment]
Cool. I didn't know about units feedback for this.
