### ISSUE TITLE
ULS UNITS - Section heading with bg color should match header color

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#617]
Currently we have section heading for the "Filter by" and various other things on unit sites (see below). I want to set up a class that we can add to each of these so that the background color is defined by the header color of each site to avoid inconsistencies. I'm going to make this adjustment on CULU to be included in the next upstream.

<img width="372" alt="Screen Shot 2019-11-20 at 12 13 13 PM" src="https://user-images.githubusercontent.com/29164102/69261235-38d60380-0b8f-11ea-900d-7876aae2ac1e.png">
<img width="412" alt="Screen Shot 2019-11-20 at 12 13 23 PM" src="https://user-images.githubusercontent.com/29164102/69261239-3a9fc700-0b8f-11ea-8a79-537a4d832566.png">
<img width="606" alt="Screen Shot 2019-11-20 at 12 13 43 PM" src="https://user-images.githubusercontent.com/29164102/69261242-3bd0f400-0b8f-11ea-8479-3332f9fe67ed.png">

**Comment by kevinkidwell** [comment]
This has been added to CULU.

**Comment by manolobevia** [comment]
@kevinkidwell the background header color is defined via customizer/kirki. You can get the hex color from there. I agree we need to be consistent with the visuals for the side bars, arrow links, bullets, headers treatment (Law shouldn't use their own title headers), etc. Before start coding we should  decide what is going to be the visual treatment, then code. For example, create a visual for side bar components like filters, popular topic, news (vet/hotel homepage), etc. I would like to avoid round corners treatment since it doesn't go with the look and field of the theme. I prefer to do some visual treatment of these components first. I have been adding these inconsistencies on different issues. How do we add these components? One solution is to create an elementor widget, another create a block template in elementor. We are at the end of November, and I don't think we should be doing mayor changes either. Are you thinking overriding the classes in elementor for now?

**Comment by kevinkidwell** [comment]
I think once we get into the new year we can start looking at some of those consistencies for all of those elements. For now, yes, I'm just going to override the elementor class with that new one. When we go through each site to add that class in, we'll also remove rounded corners from any of those ones that have them because I agree, doesn't fit the look.

**Comment by manolobevia** [comment]
Perfect!! Thanks.
