### ISSUE TITLE
ULS UNITS Display library spaces hours plugin.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#63]
We have the functionality created for displaying when libraries open/close like VET, [HOTEL](https://api3.libcal.com/api_hours_today.php?iid=973&lid=3322&format=html&systemTime=0), etc. 

Other libraries like MANN, [LAW](https://api3.libcal.com/api_hours_today.php?iid=973&lid=3476&format=html&systemTime=0), etc display spaces/services are time availability. This information is important for users to be displayed in their respective unit library websites.

- [x] Gather requirements
- [ ] Create UI / visuals
- [x] Decide best solution for displaying this type of content: shortcode, customizer, etc.

**Comment by tap87** [comment]
@manolobevia @kevinkidwell I found a wordpress plugin for libcal hours from the University of California, San Francisco, not sure if this is going to fit the requirements. https://github.com/ucsf-ckm/wplibcalhours

**Comment by tap87** [comment]
I have been working on the plugin based on the hours gem I created for Mann Library. However, it would be ideal to decide the functionality for the plugin since it will be used across multiple libraries. As a start, I am providing information on the various functions for the hours gem used by Mann.

**Functionality in the Mann Library Hours ruby gem:**

1. Daily Hours:
Get the status of the library (Open or Closed)
Get the status of a department within a library (Open or Closed)
Get the open until time if open today, or next open time if closed (the library as well as each department within the library) (e.g. until 5 pm, or Open 24 hours, or next open Jan 07 at 8 am)

2. Weekly Hours:
Makes an array of weekly hours for the library and each department within, parsed on the front end for the layout. Mann groups various departments into separate sections for various services and this is hardcoded into the layout. LibCal api isn't useful here since it just basically returns either a library or a department within a library and no other additional information can be provided to group the various department within the library.

3. Monthly hours
Use the generated code from LibCal

**Comment by tap87** [comment]
@manolobevia Do you have permission on GitHub to create a private repo under cul-it? I don't. I have some working code for the plugin that I would like to push up. If you can, please create a repo named wp-libcal-hours

**Comment by manolobevia** [comment]
@tap87 I don't have permission. Do you have @jgreidy?

**Comment by manolobevia** [comment]
@tap87 re: functionality. It could be great if we can provide that type of functionality. Thanks.

**Comment by tap87** [comment]
@gdelisle Could you please create a private repo named wp-libcal-hours on GitHub in cul-it? Thanks.

**Comment by gdelisle** [comment]
I've created the repo and given access to the new uls access group.

**Comment by tap87** [comment]
@manolobevia The basic iteration of the plugin has been uploaded to the repo: https://github.com/cul-it/wp-libcal-hours Feel free to download and test. It pretty much replicates the today's hours feature on Mann Library. Status: Open/Closed. And Open Until x am/pm or Next open at x am/pm
