### ISSUE TITLE
ULS UNITS - Multiple Hours on homepage

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#658]
Components:  
Create UI Layout, pull hours and display properly, create shortcodes and logic.  Hinderance: fit into the design of the page

Units:  
Mann, Olin/Uris

Effort:  
Medium

**Comment by kevinkidwell** [comment]
@manolobevia I have a couple of questions for you about the layout on this. I know that you shared this about a month ago for the design: https://culib.slack.com/files/U2464CHE3/FSWD43S9H/olin-uris.png

From that image, I have these questions:
1. Is that the layout that we want to go with for these?
2. Thinking about this on Mann, the Lobby that they'll use as the 2nd hours won't have an email (and is the same location, basically) so would it make sense to have the email/location for both rows?
3. Do we have the capability to add a different email for Olin and Uris so the email icons go to the respective locations if we want to have it on both lines? Do Olin and Uris share a ref email so that there would only need to be one?
4. Do we have the ability to edit the library-hours template part for those units using two different header hours? I think the only way to have this working is to pass in the Library ID so I'm hoping that we can create a new template part in the child theme for those units, maybe?

Some of the work that I've done on this so far just to keep tabs and so I remember when I'm back from D4D:
- Updated the weekly hours (full hours) display so that it is now creating/displaying on a unique div if two different shortcodes exist on the same page. Previously this was trying to put two different things into one div ID so it only took the last one.
- Created a new shortcode for the header that can be called on units that have 2 hours to display. This utilizes the functions already in place but requires the passing of the Library ID to be able to know which unit to display.
- Updated the `get daily hours function` to allow passing in the LID.
- Updated the transient key used for caching so that now it appends the LID to it. This was required to display 2 unit hours in the header, otherwise it would just show the first cached data for both hours.
- None of these changes will affect the functionality in the way units with only 1 hours display work, it's still the same functions as before (no updates needed).
