### ISSUE TITLE
UWS UNITS - Granular Elementor Permissions

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#667]
Components:  
Define widgets that users are able to use and give control based on WP roles to specific widgets

Units:  
All

Effort:  
S (determination) - ? dependent upon outcome

**Comment by kevinkidwell** [comment]
I was starting to get back into this today and did a bit more research. It turns out back in May, this was created: https://github.com/helloideabox/elementor-widget-manager. I had to update Elementor locally to avoid a console error, so if we update Elementor and Elementor Pro on all the unit sites that won't be a problem.

This plugin doesn't work with the Pro version elements and does not allow a breakdown by roles. There's an issue on the plugin repo already about the Pro issue but there hasn't been any comment on that yet. I think my approach is going to be to change from building from scratch to extending the capabilities of this plugin, since it has a sound foundation already.

Steps in development will be:
1. Get this to work with Elementor Pro widgets.
2. Add the ability to deactivate by role instead of a blanket deactivation of widgets.

**Comment by JesiBuell79** [comment]
@mhk33 - do we still need this granular permissions for unit sites?

**Comment by mhk33** [comment]
@JesiBuell79 I don't know, it's been set up for a while so maybe things are fine as is.

**Comment by JesiBuell79** [comment]
Closing
