### ISSUE TITLE
ULS UNITS - Change focus of 'Chat with Us' button

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#760]
We have to tab until the end of the page to hit the Chat with us button. I think after user tabs on the notification banner link alert, the next focus element should be the Chat btn. 

User case:
As a user with some sight disability, I think I want to focus soon on this feature since library is closed, and I need help as soon as possible. Also, people ignore footer very often. 

What do you think @mhk33 @kevinkidwell ?

**Comment by kevinkidwell** [comment]
Melissa and I chatted about this a bit whenever we were implementing these on the various sites. I think it's better to have it as the last focus because then it allows users to go through all of the content on the page first and have that be the focus before getting to the chat widget. The chat functionality is really more of a secondary feature of the site because they should be there to see the content of any given page and then if there are questions, they have the option to chat. The workflow I would think that users would typically do is looking for something specific on a page, then if they don't find it, they would either search again, try a different page, or find a way to contact someone.

From an implementation standpoint, if we were to try and put it after the navigation, that would require something in the theme and likely a custom widget. Each unit site has a different widget with their own hash for being able to track traffic analytics, so it's not something that we could put it into the theme once and it be what they need.

**Comment by mhk33** [comment]
I agree, I think it's OK that the chat is in the footer and loads toward the end on keyboard nav.
