### ISSUE TITLE
Hours not showing up on Africana site in Chrome - swiper.min.js

### ISSUE THREAD

**Issue by jgreidy** [cul-it/uls#789]
While writing a response to a ticket from SiteImprove, I re-enabled their WordPress plugin to test. The hours continued to display in FireFox, although the CORS message appears in the console.

When I tried the page on Chrome, the hours did not show, and I saw these messages in the console:

```
DevTools failed to load SourceMap: Could not load content for https://africana.library.cornell.edu/wp-content/themes/culu/js/swiper/swiper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for https://africana.library.cornell.edu/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

I left the SiteImprove plugin activated, since the hours were showing in FF and disabling it did not make the hours show in Chrome.

**Comment by manolobevia** [comment]
@jgreidy RE: I left the SiteImprove plugin activated, since the hours were showing in FF and disabling it did not make the hours show in Chrome.

We should keep SiteImprove plugin disabled, so Chrome users are able to display full hours.

Here is the solution:
https://stackoverflow.com/questions/44267503/devtools-failed-to-parse-sourcemap

This is due to the settings of chrome, for example in FF this error warnings not happens. To fix it go to Developer Tools Settings of Chrome, and uncheck:
"Enable JavaScript source maps"
"Enable CSS source maps"
Then refresh Chrome.

After that, I have enabled siteimprove, but no full hours display. Then disabled again.
