### ISSUE TITLE
Update colors of Easy Notification Bar

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#804]
The [main library site](https://library.cornell.edu/) has updated language and colors for the banner about COVID-19. I tried to change the colors on a unit site but it seems like they're coded into a stylesheet. Is there a way to make those colors pull from the customizer selection so that they'll always match whatever colors are chosen? Then, if they change them on us again, we can update all on the front end.

**Comment by mhk33** [comment]
Good idea to make this easily changeable. I suspect the background color will be changing soon. That teal is a bit much, IMO.

**Comment by manolobevia** [comment]
The bg color of the banner and the text are customizable with the customizer. The button color (text link), how it is called by the banner, are added to the CULU css. The reason I did that was to be able to control the color of the link, since the customizer apply same color to text and "button". I'll remove the css on culu.

**Comment by manolobevia** [comment]
Now, I remember what I did. As you can see in the image below, the plugin adds a BG color to the button link base on the BG of the container. So I had to do remove the btn BG with css. I did the changes on CULU, we will have to do another upstream. All this will work, if we keep the COVID button link text in white.
<img width="1100" alt="Screen Shot 2020-05-06 at 4 30 11 PM" src="https://user-images.githubusercontent.com/8395482/81225323-0ee69100-8fb7-11ea-962b-3d894e2e3f37.png">
