### ISSUE TITLE
Determine life expectancy of Sassafras

### ISSUE THREAD

**Issue by cappadona** [cul-it/uls#818]
To inform longer term implementation of software availability. Will it become the single data source for all units? See #816 for background.

**Comment by cappadona** [comment]
According to Pete Magnus via private slack message on 5/19/2020: "My understanding is that there are labs on campus they will still be supporting.  The units will be charged a fee for the lab support.  My understanding is that they will continue to need the Sassafras service for the Apps on Demand licensing."

_Originally posted by @ajs17 in https://github.com/cul-it/uls/issues/753#issuecomment-631011873_

@cul-it/clo-content-group Based on this response, do we want to pursue the Sassafras API as the data source for software availability?

**Comment by kevinkidwell** [comment]
@cappadona I think it would make sense to work with the API in this case so that we won't have to rely on manual curation of this list.

Thinking back to the software names, if we can work with Sassafrass to be able to get "nice names" for those to make it easier on our end that would be good. If it turns out they can't do it (or won't), we'd want to build in that renaming in the plugin on our end so that whatever we display to the end user will be clear. That path would mean more updates from a developer to keep those names up to date of any new software but I think we could establish communication with Pete's team to stay in the know and the bit of extra dev time is worth it for the end user experience.

@sew268 @arh269 @eeh53 do you have any thoughts on this?

**Comment by sew268** [comment]
@kevinkidwell I think what you propose makes a lot of sense!  I'm in favor of your suggestion but will defer to others (@arh269 @eeh53 ) if they spot any reasons not to go this route.

**Comment by cappadona** [comment]
Team agreed (2020-06-01) to use Sassafras API for data source moving forward
