### ISSUE TITLE
Upstream Release/v1.4.3

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#851]
@kevinkidwell @cappadona let's add here what needs to be added to the next upstream.

**CULU theme next release**

**Plugin updates**

**New plugins**:
 - [Redirection](https://wordpress.org/plugins/redirection/) #850

**Comment by kevinkidwell** [comment]
I was working on floor maps for ILR today and realized that we'll need to add this plugin for those displays, so should put it in the upstream:

[Insert Pages](https://wordpress.org/plugins/insert-pages/)

**Comment by kevinkidwell** [comment]
Custom Loop plugin has been updated and is ready to be included in the next upstream. If the upstream goes out with the CULU theme update, don't include this version until that's released.

https://github.com/cul-it/wp-custom-loop-widget/releases/tag/v1.2.0

**Comment by manolobevia** [comment]
@kevinkidwell I will be doing changes on the partials for all staff and single staff. I need to update the display of a couple of fields. Those fields are using text area ACF type,  and now will be using taxonomy ACF in preparation for the Sfaff refactoring. I would like to include these changes too in the next upstream.

**Comment by manolobevia** [comment]
@kevinkidwell I am using your latest release on culu local. I have noticed when I select `All Units - Staff profile` and publish, I get server error (500 error).

**Comment by manolobevia** [comment]
@kevinkidwell I am getting this error below on CULU dev.
			
`Warning: constant(): Couldn't find constant CUL_UNIT in /srv/bindings/0c4fbfeed2364c4ba67eac1c7695ef21/code/wp-content/plugins/wp-custom-loop-widget-master/widgets/custom-post-loops.php on line 181`

**Comment by kevinkidwell** [comment]
@manolobevia Is your local culu instance running the latest code from https://github.com/cul-it/wp-cul-theme-culu? It hasn't been put out in a release yet or pushed to the unit sites but you have to use that, since the constant is added with @cappadona's yml commits.

**Comment by jgreidy** [comment]
I'm starting to work on this now. Is the theme up to date?

**Comment by jgreidy** [comment]
I can not access Elementor Pro using the account listed in LastPass.

**Comment by cappadona** [comment]
@jgreidy We haven't cut a new release for the CULU theme just yet. Manolo is still [finalizing the staff profiles](https://github.com/cul-it/wp-cul-theme-culu/pull/22).

**Comment by jgreidy** [comment]
I can not download the new wp-rss-keyword-filtering plugin - licenses expired.

**Comment by kevinkidwell** [comment]
@jgreidy Did you use the account with the email mre2@cornell.edu? We had all information moved to that account and it says active through August 1, 2021. I'll go in and remove the other account for that plugin.

**Comment by kevinkidwell** [comment]
Another update to Custom Loop Plugin is ready to be included in the upstream. Instead of v1.2.0 we can now use v1.2.1. https://github.com/cul-it/wp-custom-loop-widget/releases/tag/v1.2.1

**Comment by kevinkidwell** [comment]
New version of the Hours plugin needs to also go in this upstream. The issue with hours not displaying properly for Engineering has been fixed in v2.0.3. https://github.com/cul-it/wp-libcal-hours/releases/tag/v2.0.3

**Comment by jgreidy** [comment]
It ended up taking 3 releases to get this done.


## [v1.4.5] - 2020-08-14
### Added
- Redirection - 4.8 - [changelog](https://wordpress.org/plugins/redirection/#developers)
- Anywhere Elementor - 1.2.2 - [changelog](https://wordpress.org/plugins/anywhere-elementor/#description)
## Changed
- wp-custom-loop-widget v1.2.1 - see [Changelog](https://github.com/cul-it/wp-custom-loop-widget/blob/master/CHANGELOG.md)
- wp-libcal-hours update - v2.0.3 - see [Changelog](https://github.com/cul-it/wp-libcal-hours/blob/dev/CHANGELOG.md)
- Advanced Custom Fields Pro - version 5.8.14 - see [Release Notes](https://github.com/cul-it/advanced-custom-fields-pro/blob/master/readme.txt)
- custom-post-type-ui update - 1.7.5 - see [CHANGES](https://github.com/WebDevStudios/custom-post-type-ui/)

## [v1.4.4] - 2020-08-14
### Changed
- created this version since the v1.4.3 tag is already used

## [v1.4.3] - 2020-08-03
### Added
- Add symfony/yaml dependency - Used downstream by CULU theme to support central config.
### Changed
- update faye-websocket for [GHSA-2v5c-755p-p4gv](https://github.com/cul-it/ci-jenkins-pantheon-wordpress/network/alert/Gemfile.lock/faye-websocket/open)
- wordpress-composer 5.5 update WordPress core - see [Field Guide](https://make.wordpress.org/core/)
- Advanced Access Manager 6.6.0 - see [Release Notes](https://wordpress.org/plugins/advanced-access-manager/#developers)
- Advanced Custom Fields: Image Aspect Ratio Crop Field - 3.4.0 - see [Changelog](https://wordpress.org/plugins/acf-image-aspect-ratio-crop/#developers)
- Advanced Custom Fields Pro - version 5.8.13 - see [Release Notes](https://github.com/cul-it/advanced-custom-fields-pro/blob/master/readme.txt)
- classic editor - version 1.6 - see [Changelog](https://wordpress.org/plugins/classic-editor/#developers)
- Coming Soon Page & Maintenance Mode v5.1.3 update - [Changelog](https://wordpress.org/plugins/coming-soon/#developers)
- Elementor 2.9.14 - see [Changelog](https://wordpress.org/plugins/elementor/#developers)
- FileBird - 4.0.5 - see [Change Log](https://wordpress.org/plugins/filebird/#developers)
- google-analytics-dashboard-for-wp - 6.2.2 - see [Changelog](https://wordpress.org/plugins/google-analytics-dashboard-for-wp/#developers)
- json-content-importer - update 1.3.9 - see [changelog](https://wordpress.org/plugins/json-content-importer/#developers)
- kirki customizer framework- 3.1.5 - see [Changelog](https://wordpress.org/plugins/kirki/#developers)
- Relevanssi - 4.8.0 - see [Changelog](https://wordpress.org/plugins/relevanssi/#developers)
- WP Mail SMTP 2.2.1 - [Changelog](https://wordpress.org/plugins/wp-mail-smtp/#developers)
- [CULU theme v1.4.1](https://github.com/cul-it/wp-cul-theme-culu/releases/tag/v1.4.1)
