### ISSUE TITLE
Add hours status to Engineering library.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#860]
Screenshot taken at 6:21pm

![Screen Shot 2020-08-11 at 6.21.38 PM.png](https://images.zenhubusercontent.com/58ffa2ca51aa2c30577c6f84/11c0a94f-7d5a-4235-b345-c34550a47b6d)

**Comment by kevinkidwell** [comment]
There's something odd in the way this is displaying because of the logic in the plugin when it relates to Engineering and PSL. I've put a fix in place that will allow it to show now but honestly the code is a bit of a mess and can be difficult to look through to find what's wrong. I want to clean it up in the near future so will make an issue for that. The fix for this is in https://github.com/cul-it/wp-libcal-hours/releases/tag/v2.0.3
