### ISSUE TITLE
Asia Meeting Prep

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#882]
Prep items for the meeting with Jeff from Asia on 9/22.

Checklist for us:
- [x] Add floor maps to site
- [x] Remove/change directions to "book stack maps" to be Floor Maps
- [x] Make sure that no links go out to current site
- [x] Combine Find A Space and Study Spaces pages, the first has no content
- [x] Build index for Databases, Guides, and other custom post types in Relevanssi and FacetWP
- [x] Change Resources navigation to list out the custom post types for resources instead of current list
- [x] Fix styling of all the links (fixed all links I could find)
- [x] Lockers & Carrels to Lockers, make it page with the information for that, Use the Library - Spaces without the Locker info

List of tasks for Jeff:
1. Review the list of staff and let us know who needs to stay.  Once we have the list of staff we can complete the staff directory page and then work on the feed of staff onto the appropriate collections pages.
2. Create content for all the landing pages that correlate with the top level navigation: About Us, Collections, Resources, Use the Library, Services, News & Events
3. Review content on the student employment page and potentially reorganize
4. Broken Links – the list of broken links is in the Asia Content folder in Box: review and update/delete
5. Think about how you want to handle News & Events – there doesn’t seem to be a lot of ‘news’ so perhaps highlight exhibits instead?  Could do a feature box on the homepage to highlight new and notable things within Kroch Asia or if you are committed to having more frequent news, you could do a blog 
6. Logo in the footer – do you want a Dept logo?  College logo?  Or no logo at all?
7. Standardize some of the content on country pages – particularly South Asia
8. Review the list underneath Resources in the top level nav – we could change it to highlight the following: Databases, Subject Guides, Books, Book Chapters, Other Resources

Post meeting to-do list:
- [ ] Check content display of all main Nav pages to be sure it's how it should be.
- [ ] Adjust any content for News & Events pages
- [x] Update footer contact information and navigation

**Comment by kevinkidwell** [comment]
New items for Jeff:
1. Spaces page - Rawson Reading Room - Needs to have some information about this room
2. Under Use the Library - would it be worthwhile to break out Spaces as Reading Rooms, Lockers, Carrels & Research Spaces? Services - Lockers & Carrels to Lockers, make it page with the information for that, Use the Library - Spaces without the Locker info.
3. Review floor maps, indicate if any numbered items should not be numbered or if items are missing that should be numbered, give text for numbered areas. All stairs, elevators, and restrooms must be numbered if publicly accessible.

**Comment by sew268** [comment]
**Development Team To-do list:**

All current staff on the existing Asia site need to remain.  Add filter option at the top similar to Mann to allow for people to select: Echols, Wason, South Asia, LIbrary Technical Services.

Addition to the staff profiles, ability to add country and language expertise. 

Need to redo feed of staff profiles onto the appropriate collections pages

Resources landing page - needs to show all resources combined into one and then be able to filter through

Remove book chapters from Resource navigation and add Library Guides

Look at feeding in department events and library hosted events from localist (potentially post launch) 

Check that South Asia’s Research Tools have been brought over, as well as electronic resources.  

Addition of option for a text box with customizable content at the top of each country page

Change ‘News & Events’ to ‘Events’ and remove sub items under it

On country pages for each feature box, make it possible to flag items as featured that you want to appear in these boxes rather than have the feed come in alphabetically.  

Update links on homepage so they link to pages on the dev site.

**Asia Staff To-do list:** 

Create content for all the landing pages that correlate with the top level navigation: About Us, Collections, Use the Library, Services, News & Events
Adding ability to filter by collection on the resources landing page.  This is possible but someone from Asia staff would have to update all the custom posts ~3000 to add this tag.  Just need to know if this is a priority and we can add the tag option on the backend and show someone how to add the tags.  

Review student employment content and potentially reorganize

Review the broken links in the Box folder and update - these have been migrated and are showing as broken on the dev site.  Once in, we can update the site to either remove or edit links.  Please note in Box if something should just be deleted.

Need list of department events that you would like to be feeding information from localist

Need an answer on the footer logo - do you want the department or college logo

Need to go through floor maps and let Kevin know the following: 1) information or text for those areas that are numbered 2) if any numbers exist that should not 3) if any areas are not numbered that should be.

Bridging Worlds exhibit under South Asia Collection: https://asia.library.cornell.edu/collections/southasia/bridging-worlds.  Seems like it might be better if we treated it like this: https://exhibits.library.cornell.edu/films-mills-and-poets?q? 

What new books do you want fed into the site and where?  Which call number ranges?  

Need to know which countries need the customizable text box as this needs to be done manually for each country page.  

Need some text describing the Rawson Reading room - does it need reservation?  What type of study happens there?  How many people does it hold?  

Request was made that on country pages for each feature area i.e. Books, databases, subject guides, etc., make it possible to tag items as “featured” so that it is possible to customize what appears in these boxes rather than have the feed come in alphabetically.  Note: it is one option or the other - either items get tagged as featured for all country pages or items are fed in alphabetically, there is no option to allow the flexibility for both.    

Need a list of names of people who would be content editors on the site and then we can schedule training on how to use WordPress.

**Comment by manolobevia** [comment]
> * All current staff on the existing Asia site need to remain.  Add filter option at the top similar to Mann to allow for people to select: Echols, Wason, South Asia, LIbrary Technical Services.

@sew268 @kevinkidwell besides filtering by country (around 15 countries), Asia site needs a filter by collections + LTS?

**Comment by kevinkidwell** [comment]
@manolobevia we don't need to filter by country for Asia. The extra filters that we would need tor Asia staff are Collections (plus LTS) and Language, I think. I'm currently using Department to show the collection that staff belong to so we can just use that as the filter for collection/lts instead of having to add a whole new field.

**Comment by manolobevia** [comment]
@kevinkidwell great! In that case, we have all the necessary filters. I have already created the filter for languages (https://github.com/cul-it/wp-cul-theme-culu/pull/37).

**Comment by JesiBuell79** [comment]
@sew268 - do you know if this ticket is still needed?
