### ISSUE TITLE
Make header section on homepage consistent across all units.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#901]
<img width="1268" alt="Screen Shot 2020-10-12 at 10 01 23 PM" src="https://user-images.githubusercontent.com/8395482/95807089-4fb9a300-0cd7-11eb-92ac-b0c9af826980.png">

<img width="1288" alt="Screen Shot 2020-10-12 at 10 01 35 PM" src="https://user-images.githubusercontent.com/8395482/95807096-51836680-0cd7-11eb-9688-cbd4be215c9d.png">

<img width="1330" alt="Screen Shot 2020-10-12 at 10 02 10 PM" src="https://user-images.githubusercontent.com/8395482/95807099-521bfd00-0cd7-11eb-8036-bd5a199e769b.png">

**Comment by kevinkidwell** [comment]
@manolobevia Can you keep me updated with what you decide to do with these headings? So far this has been part of the customization that units are able to do, which is why they're different across units. I know that Management specifically was adamant about having that background color behind their headings on the homepage (like you see on Law's screenshot for the first 2). Depending on what changes are made, we'll have to make stakeholders aware of what headings will look like.

Also, since they can edit these in Elementor, they can get into the styling portion and change it. I'm not sure how we could restrict that to keep them from changing the look around again.

**Comment by sarah-cul** [comment]
@JesiBuell79 @mhk33 
This issue is 3 years old, it may no longer be relevant. After viewing the unit sites, they appear to have a headers that are uniform in size.

**Comment by mhk33** [comment]
That sounds right, @sarah-cul, I think it's OK to close it.
