### ISSUE TITLE
https://dev-uls-asia-library-cornell-edu.pantheonsite.io/admin doesn't take users to WP admin page.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#928]
`https://dev-uls-asia-library-cornell-edu.pantheonsite.io/admin` is taking users to `https://dev-uls-asia-library-cornell-edu.pantheonsite.io/resources/administration-of-radio-film-and-television-of-guangxi-%e5%b9%bf%e8%a5%bf%e8%87%aa%e6%b2%bb%e5%8c%ba%e5%b9%bf%e6%92%ad%e7%94%b5%e8%a7%86%e5%b1%80/`
For consistency with other units, users should access using  `<asia home url>/admin`, or with the footer staff login link ( `<asia home url>/admin`).

**Comment by kevinkidwell** [comment]
@manolobevia This has happened on a number of units and all we've done is change the slug for the page it redirects to. I don't know how many of these Asia has, or how much sense the slug would make when removing that.

I think we need to look into how to set it so that <url>/admin always goes to <url>/wp-admin, which would probably be somewhere in the theme. This might be that we need make an explicit redirect declaration but I think if we can do it at the theme level. It will avoid this on all the sites if content editors add content with "admin" in the slug, which any unit could have done already if adding new resources/posts.

**Comment by kevinkidwell** [comment]
@manolobevia To get around the issue with the slugs, we can use the Redirection plugin that we have installed and set it up in there that /admin goes to /wp/wp-admin and it will override the slug redirect that's been happening. I'll go through and update this on all the unit sites so that we don't have to keep worrying about this happening anywhere.

**Comment by kevinkidwell** [comment]
Redirect has been added to all unit sites, including dev instances for Mann, Olin/Uris, and Asia.
