### ISSUE TITLE
Build upstream v1.4.10

### ISSUE THREAD

**Issue by jgreidy** [cul-it/uls#946]
No WordPress update this time

**Comment by manolobevia** [comment]
@kevinkidwell do you need to include any custom plugin updates?

**Comment by kevinkidwell** [comment]
We do have new code for the Hours plugin and Custom Loop plugin that should be pushed. I wasn't sure where we left them when we last worked on it so I was hoping to discuss with the group on Monday. There are some changes to Math's hours that should be fixed in the Hours plugin (if I'm remembering correctly) and the Custom Loop plugin has stuff for Asia's site that we should push before they launch.

**Comment by jgreidy** [comment]
@kevinkidwell - sorry - I didn't see your note before I finished the build of v1.4.10. That release is ready to go. I can make the next one once all the custom code is ready.
